deploy-job:
  docker:
    - image: circleci/node:7.10
  working_directory: /tmp/my-project
  steps:
    - run:
        name: Deploy Master to Firebase
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
 version: 2

 -deploy:
   jobs:
     - deploy-job:
        filters:
          branches:
            only: master

