version: 2
jobs:
  deploy-job::
    docker:
      - image: circleci/node:7.10
    steps:
      - run:
          name: where
          command: pwd
      - run:
          name: list
          command: ls -la
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  build:
    jobs:
     - deploy-job::
        filters:
          branches:
            only: master
