version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: /tmp
    steps:
      - run:
          name: where
          command: pwd
      - run:
          name: list
          command: ls -la
      - run:
          name: find
          command: find / -name 404-page.html
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  build:
    jobs:
     - deploy:
        filters:
          branches:
            only: master
